### ISSUE TITLE
Missing install steps in README

### ISSUE THREAD

**Issue by Orabig** [mklements/OLED_Stats#11]
I had to do the following steps (which are not mentionned in the README) to make the scripts work :

```
sudo apt-get install python3-rpi.gpio libopenjp2-7 libtiff5
sudo pip3 install Pillow
```

After that, they work perfectly.

**Comment by mklements** [comment]
What OS are you running this on?

**Comment by Orabig** [comment]
It's Raspbian GNU/Linux 10 (buster) (but with minimal version, without Xorg. Who needs a graphical environment on a remote RaspberryPi anyway ? :D )

**Comment by Martius108** [comment]
Since Raspian OS bookworm this tutorial is not working anymore. It seems that there is a virtual environment for this installation needed. Please update your tutorial. I was not able to install adafruit-python-shell and got stuck there.

**Comment by mklements** [comment]
The script is intended to be used with Raspberry Pi OS. Different Linux distributions will require different/missing libraries to be installed.
