### ISSUE TITLE
Installation on bookworm requires a virtual environment and is not working 

### ISSUE THREAD

**Issue by Martius108** [mklements/OLED_Stats#12]
Hello,

I tried to follow your tutorial on a Raspberry Pi 5 and Raspbian bookworm.
I found out that a virtual environment is required for pip3 installations. I  created a venv "project" folder.
This is what I got:

`Successfully installed setuptools-69.0.3
(project) pi@raspberrypi:~ $ pip3 install --upgrade adafruit-python-shell
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: adafruit-python-shell in ./project/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: clint in ./project/lib/python3.11/site-packages (from adafruit-python-shell) (0.5.1)
Requirement already satisfied: Adafruit-PlatformDetect in ./project/lib/python3.11/site-packages (from adafruit-python-shell) (3.58.0)
Requirement already satisfied: args in ./project/lib/python3.11/site-packages (from clint->adafruit-python-shell) (0.1.0)
(project) pi@raspberrypi:~ $ wget https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/raspi-blinka.py
--2024-01-18 09:50:28--  https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/raspi-blinka.py
Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443 ... verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet ... 200 OK
Länge: 5481 (5,4K) [text/plain]
Wird in »raspi-blinka.py.1« gespeichert.

raspi-blinka.py.1   100%[===================>]   5,35K  --.-KB/s    in 0,004s  

2024-01-18 09:50:28 (1,33 MB/s) - »raspi-blinka.py.1« gespeichert [5481/5481]

(project) pi@raspberrypi:~ $ python3 raspi-blinka.py
Installer must be run as root.
Try 'sudo python3 raspi-blinka.py'
(project) pi@raspberrypi:~ $ sudo python3 raspi-blinka.py
Traceback (most recent call last):
  File "/home/pi/raspi-blinka.py", line 12, in <module>
    from adafruit_shell import Shell
ModuleNotFoundError: No module named 'adafruit_shell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/raspi-blinka.py", line 14, in <module>
    raise RuntimeError("The library 'adafruit_shell' was not found. To install, try typing: sudo pip3 install adafruit-python-shell")
RuntimeError: The library 'adafruit_shell' was not found. To install, try typing: sudo pip3 install adafruit-python-shell
(project) pi@raspberrypi:~ $`

It seems I’m caught in a loop because Adafruit Python Shell is not installed (properly).
Btw I’m wondering why I shall use sudo in the virtual environment. Normally this shouldn’t be used here as far as I know.

As you can see adafruit-python-shell is installed but adafruit_shell is not found (see above).

`(project) pi@raspberrypi:~ $ pip3 list
Package                 Version
----------------------- -------
Adafruit-PlatformDetect 3.58.0
adafruit-python-shell   1.8.0
args                    0.1.0
clint                   0.5.1
pip                     23.0.1
setuptools              66.1.1
wheel                   0.38.4
(project) pi@raspberrypi:~ $ pip3 list | grep -i adafruit
Adafruit-PlatformDetect 3.58.0
adafruit-python-shell   1.8.0
(project) pi@raspberrypi:~ $`

See also adafruit/Adafruit_Blinka/issues here on GitHub

**Comment by Martius108** [comment]
Hello,

I finally got your stats.py to work on bookworm. But it needed a virtual environment (env) as mentioned above.
I tried to make it autostart with boot but it doesn't work yet. This is what I tried:

I created a cron job like this:
`@reboot /bin/bash -c "/home/pi/cron_stats.sh" &`

Then I created the cron_stats.sh file like this:
`cd /home/pi/OLED_Stats

source env/bin/activate

/usr/bin/python3 -m stats.py`

And made it executable with this command:
`sudo chmod +x /home/pi/cron_stats.sh`

Can anyone help me out and tell me what I did wrong?

**Comment by victor7376** [comment]
can you explain how you got it to work as I'm facing the same issue with running the script stating 'no module pil' cheers

**Comment by victor7376** [comment]
Nevermind I've got that part now done,

For others you need to execute the commands within the venv but without the sudo command.

When it comes to python-pil you change it to pip install Pillow

Once this is all done, you exit the venv with deactivate, you then follow the instructions to start up the crontab but instead of typing in

@reboot python3 /home/pi/stats.py &

change it to

@reboot /home/pi/(name of your venv)/bin/python3 /home/pi/stats.py &

For example as the OP's venv is 'project' this would look like:

@reboot /home/pi/project/bin/python3 /home/pi/stats.py &

You'll now have a working stats display in bookworm.

**Comment by Martius108** [comment]
Check this issue which I started:
[https://github.com/adafruit/Adafruit_Blinka/issues/782](url)
That helped me to find a working solution

**Comment by victor7376** [comment]
yeh Just updated my post to confirm how to get the stats.py script working at boot on bookworm too ;)

**Comment by MemerAus** [comment]
> Hello,
> 
> I finally got your stats.py to work on bookworm. But it needed a virtual environment (env) as mentioned above. I tried to make it autostart with boot but it doesn't work yet. This is what I tried:
> 
> I created a cron job like this: `@reboot /bin/bash -c "/home/pi/cron_stats.sh" &`
> 
> Then I created the cron_stats.sh file like this: `cd /home/pi/OLED_Stats
> 
> source env/bin/activate
> 
> /usr/bin/python3 -m stats.py`
> 
> And made it executable with this command: `sudo chmod +x /home/pi/cron_stats.sh`
> 
> Can anyone help me out and tell me what I did wrong?

I have tried this and the chmod comment won't start it for me 
`sudo chmod +x /home/pi/cron_stats.sh`

I had this working on the same RPI4 as a Dogenode, now trying to get it to work under bookworm and no good.

**Comment by MemerAus** [comment]
> Hello,
> 
> I tried to follow your tutorial on a Raspberry Pi 5 and Raspbian bookworm. I found out that a virtual environment is required for pip3 installations. I created a venv "project" folder. This is what I got:
> 
> `Successfully installed setuptools-69.0.3 (project) pi@raspberrypi:~ $ pip3 install --upgrade adafruit-python-shell Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple Requirement already satisfied: adafruit-python-shell in ./project/lib/python3.11/site-packages (1.8.0) Requirement already satisfied: clint in ./project/lib/python3.11/site-packages (from adafruit-python-shell) (0.5.1) Requirement already satisfied: Adafruit-PlatformDetect in ./project/lib/python3.11/site-packages (from adafruit-python-shell) (3.58.0) Requirement already satisfied: args in ./project/lib/python3.11/site-packages (from clint->adafruit-python-shell) (0.1.0) (project) pi@raspberrypi:~ $ wget https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/raspi-blinka.py --2024-01-18 09:50:28-- https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/raspi-blinka.py Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ... Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443 ... verbunden. HTTP-Anforderung gesendet, auf Antwort wird gewartet ... 200 OK Länge: 5481 (5,4K) [text/plain] Wird in »raspi-blinka.py.1« gespeichert.
> 
> raspi-blinka.py.1 100%[===================>] 5,35K --.-KB/s in 0,004s
> 
> 2024-01-18 09:50:28 (1,33 MB/s) - »raspi-blinka.py.1« gespeichert [5481/5481]
> 
> (project) pi@raspberrypi:~ $ python3 raspi-blinka.py Installer must be run as root. Try 'sudo python3 raspi-blinka.py' (project) pi@raspberrypi:~ $ sudo python3 raspi-blinka.py Traceback (most recent call last): File "/home/pi/raspi-blinka.py", line 12, in from adafruit_shell import Shell ModuleNotFoundError: No module named 'adafruit_shell'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/pi/raspi-blinka.py", line 14, in raise RuntimeError("The library 'adafruit_shell' was not found. To install, try typing: sudo pip3 install adafruit-python-shell") RuntimeError: The library 'adafruit_shell' was not found. To install, try typing: sudo pip3 install adafruit-python-shell (project) pi@raspberrypi:~ $`
> 
> It seems I’m caught in a loop because Adafruit Python Shell is not installed (properly). Btw I’m wondering why I shall use sudo in the virtual environment. Normally this shouldn’t be used here as far as I know.
> 
> As you can see adafruit-python-shell is installed but adafruit_shell is not found (see above).
> 
> `(project) pi@raspberrypi:~ $ pip3 list Package Version
> 
> Adafruit-PlatformDetect 3.58.0 adafruit-python-shell 1.8.0 args 0.1.0 clint 0.5.1 pip 23.0.1 setuptools 66.1.1 wheel 0.38.4 (project) pi@raspberrypi:~ $ pip3 list | grep -i adafruit Adafruit-PlatformDetect 3.58.0 adafruit-python-shell 1.8.0 (project) pi@raspberrypi:~ $`
> 
> See also adafruit/Adafruit_Blinka/issues here on GitHub

Can you do a step by step tutorial on this I can't get my head around the Virtual environment at all

**Comment by mklements** [comment]
I have updated the script and installation instructions to work on Bookworm within a virtual environment.
