### ISSUE TITLE
OLED_Stats.git -  error

### ISSUE THREAD

**Issue by lenochod-rpi4** [mklements/OLED_Stats#14]
Hello,

i´m setting OLED I2C display on RPi4. I follow your tutorial step after step, Every command ends succsesfully but I stuck on command git clone..... OLED_Stats.git without this step I can´t go to another step.
github

Using RPi4 with Raspbian Bulllseye lite 64bit. Is this just because i use version without? I connect to terminal via ssh from windows 10 ultimate x64

Where can be the problem?

Thank you very much
![github](https://github.com/mklements/OLED_Stats/assets/156958464/7fda9804-c1ba-452d-9920-de54975a0c35)

**Comment by austonpramodh** [comment]
Looks like you will need to install `git` using `sudo apt install git`

**Comment by mklements** [comment]
Yes, I have added this as an installation step now.

**Comment by lenochod-rpi4** [comment]
Thank you very much 

> Looks like you will need to install `git` using `sudo apt install git`

Thank you very much
