### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by RogueOneder** [mklements/OLED_Stats#15]
https://github.com/mklements/OLED_Stats/blame/f153be2a4971081e70037520e3094461925a4852/stats.py#L6

I am getting the following error when I try to use stats.py
(venv) pi@MyPi:~/OLED_Stats $ python3 stats.py
Traceback (most recent call last):
  File "/home/pi/OLED_Stats/stats.py", line 6, in <module>
    import board
ModuleNotFoundError: No module named 'board'

**Comment by strachtastic** [comment]
I am having this same issue.

**Comment by ooinovaioo** [comment]
I am currently also stuck in this step. It appears import board fails as mentioned above.

**Comment by mklements** [comment]
I have updated the script to use the gpiozero library which resolves this issue.
