### ISSUE TITLE
what is the purpose of the "LA" string?

### ISSUE THREAD

**Issue by yurtkuran** [mklements/OLED_Stats#16]
Thanks a million for this code! Just got it up & running.

Quick question, what is the purpose of the "LA" string is this line?

https://github.com/mklements/OLED_Stats/blob/f153be2a4971081e70037520e3094461925a4852/stats.py#L65C52-L66C5

Thanks in advance!

**Comment by marcoemil28** [comment]
I have had a similar Problems! It is also visible in the monitor.py 
`cmd = "top -bn1 | grep load | awk '{printf \"%.2fLA\", $(NF-2)}'"`
To make the monitor.py work, you would have to edit the file and replace **LA** with %% in line 70

My guess is it was a mistake.

This is the correct Code for line 66 in stats.py would be
`draw.text((0, 16), str(CPU,'utf-8'), font=font, fill=255)`

**Comment by mklements** [comment]
It is not a mistake. Linux displays CPU utilisation as load average, not as a percentage. The utilisation displayed is this load average figure. Roughly speaking a load average of 0.8 would be 80% utilisation but they're not directly convertable and load average can be higher than 1, indicating that the CPU is receiving more work than it can handle (where a CPU can't be at over 100% utilisation).
